name:                mypandoc
version:             0.1.0.0
github:              "EpitechPromo2027/B-FUN-400-MAR-4-1-mypandoc-theo.fabiano"
license:             BSD-3-Clause
author:              "Théo Fabiano"
maintainer:          "theo.fabiano@epitech.eu"
copyright:           "2024 Théo Fabiano"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/EpitechPromo2027/B-FUN-400-MAR-4-1-mypandoc-theo.fabiano#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - base

executables:
  mypandoc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mypandoc
    - base
